# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import inventaire.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='nombre_cachee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité cachée'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='nombre_total',
            field=models.PositiveIntegerField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='coordonnee',
            field=models.CharField(help_text='Doit ressembler à : -12,48, -20,-45, 2,-10 ou encore 4,5', max_length=9, validators=[inventaire.validators.validation_coordonnee]),
        ),
    ]
