# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import inventaire.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_auto_20160701_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='coordonnee',
            field=models.CharField(db_index=True, help_text='Doit ressembler à : -12,48, -20,-45, 2,-10 ou encore 4,5', max_length=9, validators=[inventaire.validators.validation_coordonnee]),
        ),
    ]
