# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_auto_20160701_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='statut',
            field=models.IntegerField(choices=[(0, ''), (1, 'Valide'), (2, 'Refusé')], default=0),
        ),
    ]
